### ISSUE TITLE
Website wiki.abmanager.tech is non-functional (click farm)

### ISSUE THREAD

**Issue by bittner** [Android-Boot-Manager/Android-Boot-Manager.github.io#5]
The URL `wiki.abmanager.tech` mentioned [in the README](https://github.com/Android-Boot-Manager/Android-Boot-Manager.github.io#how-can-i-use-it) and on https://android-boot-manager.github.io/ in the section "How can I use it?" seems to point to a parked domain. A click farm page shows.

Can this link be removed or updated?

**Comment by nift4** [comment]
Hey there, we're currently moving to https://andbootmgr.org, sites will be back up tomorrow. P.S.: we have a telegram group over at https://t.me/andbootmgr you probably want to join

**Comment by bittner** [comment]
From the Telegram group, last week:

>> The Wiki is offline?
>
> after a spam attack and hoster data loss, it's offline
> 
> we are trying to get it back up but live's busy

What do you think of migrating the Wiki content to GitHub pages or GitLab pages?

The content would then be under version control, we could still edit it collaboratively, and GitHub or GitLab would take care of securing the infrastructure.

If you're interested, I'd be ready to help.

**Comment by johnzxlin** [comment]
ITS A FAKE NEWS, ONLY DAY DREAMING. THEY WILL NEVER GAVE YOU DOWNLOAD LINK

**Comment by halal-beef** [comment]
What?

**Comment by luka177** [comment]
There are no "news" and it is already possible to download something for some selected devices.

**Comment by luka177** [comment]
Issue itself is actually fixed for loong time, so i am closing issue
